### ISSUE TITLE
Passing multiple files to psql

### ISSUE THREAD

**Issue by oschwald** [houseabsolute/Pg-CLI#1]
With `psql`, you can repeat `-f` to pass multiple files to it. As far as I can tell, this is not supported by `Pg::CLI::psql`. Would you accept a PR to add this? In particular, I am thinking of changing the type on `file` to be `Str | File | ArrayRef[ Str | File ]`.

**Comment by autarch** [comment]
Yes, this sounds fine, but can you use a coercion to make sure it's always an `ArrayRef`? That'll make the internals a bit simpler.

**Comment by autarch** [comment]
Done in 0.12
